### ISSUE TITLE
Draw.IO Application Enabled - App Icon Not Visible - Firefox and Chrome tested

### ISSUE THREAD

**Issue by compumatter** [pawelrojek/nextcloud-drawio#23]
I'm having a problem where the Icon is not visible even though it is enabled. 

https://www.youtube.com/watch?v=UiVh1EjSfWM

I am using Nextcloud 12.0.3 

Thanks.

Jay
CompuMatter

**Comment by resoli** [comment]
Same here.

**Comment by compumatter** [comment]
Thanks Resoli - that at least gives me a way to go !  I did not see that one.  

The issue is still unresolved but it makes it usable in the interim

**Comment by AugustinVoiMa** [comment]
Hello, I experience the same issue.
Unfortunately this repo seems to be outdated...

**Comment by arnowelzel** [comment]
Not all apps create their own icon, because it does not make sense in every case.

For example when you install Collabora there is also no icon for it, even though you can create new office files (documents, spreadsheets etc.) or edit existing office files in the file explorer.

Another problem is that Draw.io has no "File - Save as" yet and no Nextcloud integration in the way, that you can use a Nextcloud folder as a target to save new drawings - but this would be needed, if you would open Draw.io directly and not using a existing drawing file in the file explorer.

**Comment by dehuszar** [comment]
I'm having this issue as well.  Is there a way to get the icon to display or does one just access it through the Files app?  If so, the docs could use some clarification

**Comment by arnowelzel** [comment]
@dehuszar What exactly do you expect when there was a "Draw.io" icon in the top toolbar and you click on it?

**Comment by dehuszar** [comment]
That was the expectation, yes

**Comment by arnowelzel** [comment]
@dehuszar That's not an answer to my question. I asked: what should happen, when you click the app icon for Draw.io?

**Comment by dehuszar** [comment]
Ah, I see.  Your question read differently to me because there is no draw.io icon in the app bar for me.  I can see an option to create a draw.io file from the files app but that's it.

**Comment by arnowelzel** [comment]
@dehuszar And you can open draw.io files in the file list. So there is no need for a specific app icon.

So once again: if there was an app icon for Draw.io - what should happen when you click on it? Can you please just answer this question? Because just having an app icon without any function does not make sense.

**Comment by AugustinVoiMa** [comment]
Hey,
My previous post on this topic should have been more explained.

I ( and I guess dehuszar ) would like to have this icon in the app bar  to create a new document from scratch and then, save it (browsing to target location in a file browser)

So it would be great to have a "file" menu with saving items

**Comment by dehuszar** [comment]
@arnowelzel I'm not sure what your intention is, but the way you're communicating feels unnecessarily hostile over a simple request to get clarity / make a request.

Obviously, if I clicked on an app icon I would be taken to the draw.io app interface, the same way I would for the Notes or Mindmaps apps I use on Nextcloud.  If one goes to the actual [draw.io](https://www.draw.io/) website there are a variety of menus around file management, creating new projects, etc.  It does not leave these tasks for Google Drive or the storage destination of your choice to handle.  So having used both Nextcloud _and_ the primary draw.io implementation, I think there's a reasonable presumption that it would create an app icon unless described otherwise.

I don't _mind_ having to go through the Files app to manage the diagrams, but I feel like at least adding a sentence to the app description in the store and on project project page telling people what to expect would be an improvement.

All that the repo README has is a tightly cropped screenshot with the menu over the context and no description.

**Comment by arnowelzel** [comment]
@dehuszar sorry, it was not my intention to be hostile. I just got a bit nerved, as it seems no one reads other posts here or even tries to understand how Nextcloud works before adding a "me too" etc. without explaining anything.

As I already explained, Draw.io works like Collabora or OnlyOffice (or any other app which is registered as a handler for specific file types) - these apps also do not provide an app icon, as it is not needed at all. You create a new drawing within the file manager of Nextcloud as you would to it with a new document or spreadsheet in Collabora or OnlyOffice.

The second problem is, that apps in Nextcloud can't easily provide a "File - save as" option since there is no standard file selector in Nextcloud to do this (the box which would appear in Windows or macOS when you save a new file). Using the existing "File" menu from Draw.io does not help here either as this is not useable with Nextcloud - it just provides the XML and you can choose wether you want to download it or share it using Google Drive, OneDrive, Dropbox etc.. You also have to take into account, that a user which is allowed to view a file may not be allowed to store the file under a different name or even write files at all (see public links for office documents in Collabora or OnlyOffice).

Mindmaps is a completely different matter, as this apps do not work with files at all. It will just save everything to database tables. Therefore the **only** way to open this apps is the icon (as it is with Deck, Tasks, Contacts, Calendar etc.).

Also Notes does not allow you to save a note in a file wherever you want to - it just stores everything inside a specific folder. In fact the Notes app is more like another view for the "Notes" folder with the list of existing files to the left and an editor for the selected file.

**Comment by dehuszar** [comment]
Thanks for the explanation.  I'll try and put together a PR this weekend
for the README and maybe we can use that to close this issue
