### ISSUE TITLE
Nextcloud 15 Compatibility

### ISSUE THREAD

**Issue by Co0p3r21** [pawelrojek/nextcloud-drawio#62]
The Beta of Nextcloud 15 has started. It would be great if this draw.io app would be released for Nextcloud 15.

**Comment by violoncelloch** [comment]
Nextcloud 15 has been released today. It would be nice if you could update this app to work on Nextcloud 15! Thank you!

**Comment by xf-** [comment]
works for me after changing the max version

**Comment by violoncelloch** [comment]
@xf- you could possibly accelerate this by creating a PR for that change...

**Comment by Aschenbecher** [comment]
is Pawel still active, or someone has a working fork? :(

**Comment by janLo** [comment]
You can just clone the repo, merge the PR in and copy the result in your custom_apps dir.

**Comment by davidjgraph** [comment]
This is something of an ongoing issue. Pawel isn't willing to add an admin to this project or the nextcloud listing, which blocks it. We will be talking to NextCloud about the listing.

**Comment by violoncelloCH** [comment]
@pawelrojek thank you for merging #66

**Comment by pawelrojek** [comment]
Three full versions were released in just 10 months (13/14/15). And that's why it's all so slow.
https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

GitHub is relatively easy, you just merge PRs, and most of the PRs aren't breaking things. But no one really cares about Github code. What people really want is App Store release, so they could click the "Update" button. This is more complex. I need to test it against all the supported versions. Update changelog/readmes. Pack it, then I got to signed it and finally upload to the store (BTW, last time even the uploading was broken on the NextCloud server - it took three days to fix it)... 
This all takes way more time than merging PRs.

I consider it to be ridiculous to bump version every few months. THIS SHOULD BE DONE AUTOMATICALLY. Like it's done with browser extensions (for instance).

That's why I'm so reluctant to spend hours on "bumping versions". It's a Sisyphean task.

**Comment by janLo** [comment]
@pawelrojek you could give the app to a wider audience of maintainers, so that this burdon of work is not only yours.

An automatic bump sounds good but is sadly not always possible. It always needs manual testing.

The release process can also probably be automated to a certain point using some CI system like travis.

**Comment by davidjgraph** [comment]
I fully agree that your time is not worth nothing, this I suggested we pay you for the hours you spend on it. I hope you'll consider talking to me about that.

From our side the problem is that when a listing says "draw.io" people link the quality of a project, even if not ours, with the draw.io brand and submit support tickets to us when there's a problem. Obviously, we can't stop anyone from using open source, but if an author doesn't have the time required to maintain actively (and I fully agreed it's very boring in the case of NextCloud), we ask the project not be called draw.io (e.g. the wordpress plugin author called it drawit), to avoid these problems.

In this case, I really would accept the PRs to up the build number and just release it. If it fails users will have to care enough to submit a proper PR 8-).

**Comment by Aschenbecher** [comment]
@pawelrojek thanks for your work btw ;) looking forward to the app store release

**Comment by e-alfred** [comment]
The fast release cycle of Nextcloud and the way app versions are managed is neither pleasant for developers nor users. There are also breaking changes (from 13 to 14 it was most extreme) that cripple apps which have to be fixed for newer versions at a fast pace. All of this makes the Nextcloud app ecosystem quite unpredictable sadly.

**Comment by pawelrojek** [comment]
@davidjgraph
I get your point now. I didn't think of Draw.io as a "commercial product" before.

From now on I'm gonna try to meet the deadlines imposed by the NC team. I don't want to hurt your "brand". Draw.io is a great piece of software!

"Nextcloud Draw.io integration" is/was a side-side-side project for me... It just hasn't been a top priority for me. But I'm gonna promote it to a "full-blown side project" now 😄

If you or someone else wants to donate some $$$ then it's greatly appreciated :) But "paying me for the hours" seems too much. This is an open source project, afterall.

**Thank you for all your support to date!**
